version: '2'
services:
  mysqldb:
    container_name: devops-mysqldb
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=tpachato
    volumes:
      - /home/mysql/data:/var/lib/mysql

  devops-backend:
    image: hamzamelki/backend-tpachat-image-1.0:latest
    container_name: devops-backend
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
